const charadesBank = [
    { q: "Pikachu", i: "用马来文" },
    { q: "Cinderella", i: "用马来文" },
    { q: "TouchNGo", i: "用马来文" },
    { q: "Drinking Bubble Tea (喝珍珠奶茶)", i: "做动作" },
    { q: "Taking a selfie (自拍)", i: "用中文" },
    { q: "Going to the Gym (去健身房)", i: "用马来文" },
    { q: "Ordering GrabFood/Delivery (点外卖)", i: "用客家" },
    { q: "Camping in the rain (在雨中露营)", i: "讲话" },
    { q: "Winning the Lottery (中大奖)", i: "做动作" },
    { q: "Stuck in a traffic jam (塞车)", i: "讲话" },
    { q: "Twinkle Twinkle (星星人)", i: "用中文" },
    { q: "The Last Supper (最后的晚餐)", i: "用中文" },
    { q: "Jesus walking on Water (耶稣走在水面上)", i: "用中文" },
    { q: "Parting of the Red Sea (红海开路)", i: "用中文" },
    { q: "遛狗", i: "用中文" },
    { q: "Getting 'Ghosted' (放飞机)", i: "用客家" },
    { q: "Unboxing (开箱)", i: "用中文" },
    { q: "Spilling the 'Tea' (讲八卦)", i: "做动作" },
    { q: "Mamak Yumcha", i: "用马来文" },
    { q: "Gout（痛风）", i: "用中文" },
    { q: "High blood pressure（高血压）", i: "用客家" },
    { q: "Side-eye（翻白眼）", i: "做动作" },
    { q: "Hotpot（火锅）", i: "用中文" },
    { q: "Johnson", i: "做动作" },
    { q: "Bungee jump", i: "做动作" },
    { q: "Rummy", i: "用英文" },
    { q: "斗鸡眼", i: "做动作" },
    { q: "Scam call (诈骗电话)", i: "用英文" },
    { q: "Manicure (美甲)", i: "用中文" },
    { q: "抛柑", i: "用马来文" },
    { q: "吃柑", i: "用中文" },
    { q: "红包", i: "用马来文" },
    { q: "冲咖啡", i: "用中文" },
    { q: "Disneyland", i: "用英文" },
    { q: "Yee Ling", i: "做动作" },
    { q: "Burning the midnight oil (熬夜)", i: "讲话" },
    { q: "Praise and worship (敬拜赞美)", i: "用中文" },
    { q: "Usher（教会招待）", i: "用客家" },
    { q: "Pastor (牧师)", i: "用客家" },
    { q: "狼吞虎咽", i: "用英文" },
    { q: "乌鸦嘴", i: "用英文" },
    { q: "Visit dentist (看牙医)", i: "用中文" }
];

const hummingBank = [
    "时光大耳窿",
    "如果可以",
    "Cupid",
    "Just The Way You Are – Bruno Mars",
    "Perfect",
    "Love Story",
    "告白气球",
    "小幸运",
    "因他活着（Because He Lives)",
    "我相信（I Believe)",
    "晴天",
    "飘向北方",
    "Sugar",
    "阿拉斯加海湾",
    "在加納共和國離婚",
    "不遗憾"
];

const photoBank = [
    "夕阳",
    "小动物",
    "风景",
    "小时候的照片",
    "Sushi",
    "火锅",
    "小组组员合照",
    "月亮",
    "新年Outfit",
    "家人合照",
    "海边",
    "婚礼",
    "Rainbow",
    "植物"
];