const charadesBank = [
    { q: "Pikachu", i: "用马来文" },
    { q: "Cinderella", i: "用马来文" },
    { q: "TouchNGo", i: "用马来文" },
    { q: "Drinking Bubble Tea (喝珍珠奶茶)", i: "做动作" },
    { q: "Taking a selfie (自拍)", i: "用中文" },
    { q: "Going to the Gym (去健身房)", i: "用马来文" },
    { q: "Ordering GrabFood/Delivery (点外卖)", i: "用客家" },
    { q: "Camping in the rain (在雨中露营)", i: "讲话" },
    { q: "Winning the Lottery (中大奖)", i: "做动作" },
    { q: "Stuck in a traffic jam (塞车)", i: "讲话" },
    { q: "Twinkle Twinkle (星星人)", i: "用中文" },
    { q: "The Last Supper (最后的晚餐)", i: "用中文" },
    { q: "Jesus walking on Water (耶稣走在水面上)", i: "用中文" },
    { q: "Parting of the Red Sea (红海开路)", i: "用中文" },
    { q: "Scam call (诈骗电话)", i: "用英文" },
    { q: "Manicure (美甲)", i: "用中文" },
    { q: "抛柑", i: "用马来文" },
    { q: "吃柑", i: "用中文" },
    { q: "红包", i: "用马来文" },
    { q: "冲咖啡", i: "用中文" },
    { q: "Disneyland", i: "用英文" },
    { q: "Yee Ling", i: "做动作" },
    { q: "Burning the midnight oil (熬夜)", i: "讲话" },
    { q: "Praise and worship (敬拜赞美)", i: "用中文" },
    { q: "Usher（教会招待）", i: "用客家" },
    { q: "Pastor (牧师)", i: "用客家" },
    { q: "狼吞虎咽", i: "用英文" },
    { q: "乌鸦嘴", i: "用英文" },
    { q: "Visit dentist (看牙医)", i: "用中文" },
    { q: "蛀牙", i: "用马来文" }
];

const hummingBank = [
    "时光大耳窿",
    "如果可以",
    "Cupid",
    "Just The Way You Are – Bruno Mars",
    "Perfect",
    "Love Story",
    "告白气球",
    "小幸运",
    "因他活着（Because He Lives)",
    "我相信（I Believe)",
    "晴天",
    "飘向北方",
    "Sugar",
    "阿拉斯加海湾",
    "在加納共和國離婚",
    "不遗憾",
    "APT",
    "See you again",
    "105度的你",
    "永不失联的爱",
    "One Way",
    "那些年",
    "Horseh",
    "一切歌颂赞美",
    "恩典之路",
    "Payphone",
    "Let It Go",
    "Horseh",
    "有一种悲伤",
    "修炼爱情",
];

const photoBank = [
    "夕阳",
    "小动物",
    "风景",
    "小时候的照片",
    "Sushi",
    "火锅",
    "小组组员合照",
    "月亮",
    "新年Outfit",
    "家人合照",
    "海边",
    "婚礼",
    "Rainbow",
    "植物",
    "运动",
    "书",
    "burger/fastfood",
    "炸鸡",

];

const charadesFinalBank = [
    { q: "遛狗", i: "用中文" },
    { q: "Getting 'Ghosted' (放飞机)", i: "用客家" },
    { q: "Unboxing (开箱)", i: "用中文" },
    { q: "Spilling the 'Tea' (讲八卦)", i: "做动作" },
    { q: "Mamak Yumcha", i: "用马来文" },
    { q: "Gout（痛风）", i: "用中文" },
    { q: "High blood pressure（高血压）", i: "用客家" },
    { q: "Side-eye（翻白眼）", i: "做动作" },
    { q: "Hotpot（火锅）", i: "用中文" },
    { q: "Johnson", i: "做动作" },
    { q: "Bungee jump", i: "做动作" },
    { q: "Rummy", i: "用英文" },
    { q: "斗鸡眼", i: "做动作" },
    { q: "我要打十个", i: "做动作" },
    { q: "李小龙", i: "做动作" },
    { q: "米老鼠", i: "做动作" },
    { q: "放鞭炮", i: "用英文" },
    { q: "云霄飞车", i: "用中文" },
    { q: "拉小提琴", i: "做动作" },
    { q: "诺亚方舟", i: "用马来文" },
    { q: "夹娃娃机", i: "用中文" },
    { q: "耶稣使水变酒", i: "用马来文" },
    { q: "猩猩", i: "用客家话" },
    { q: "耶稣第三日复活", i: "用中文" },
    { q: "michael Jackson", i: "做动作" },
    { q: "功夫足球", i: "用中文" },
    { q: "打排球", i: "做动作" },
    { q: "要到舌头", i: "做动作" },
    { q: "彼得三次不认主", i: "用客家话" },
    { q: "大卫大战歌利亚", i: "用客家话" }
];

const hummingFinalBank = [
    "How Great Is Our God",
    "Hosanna",
    "Golden (kpop demon hunter)",
    "beauty and the beast",
    "Under the sea",
    "Hakuna Matata",
    "You'll Be in My Heart",
    "Humming Final 8",
    "Humming Final 9",
    "Humming Final 10",
    "Humming Final 11",
    "Humming Final 12",
    "Humming Final 13",
    "Humming Final 14",
    "Humming Final 15",
    "Humming Final 16",
    "Humming Final 17",
    "Humming Final 18",
    "Humming Final 19",
    "Humming Final 20",
    "Humming Final 21",
    "Humming Final 22",
    "Humming Final 23",
    "Humming Final 24",
    "Humming Final 25",
    "Humming Final 26",
    "Humming Final 27",
    "Humming Final 28",
    "Humming Final 29",
    "Humming Final 30",
];
